### ISSUE TITLE
.podspec version error

### ISSUE THREAD

**Issue by ghost** [greenbits/papertrail-lumberjack-ios#10]
sorry.i can't to say that the .podspec for CocoaAsyncSocket version is error . 
Please change it to a right version . hahaha. come on . it's a beautyful framework

**Comment by andrewkatz** [comment]
There is no specified version in the podspec. Can you link to what you're talking about or explain it better?

**Comment by ghost** [comment]
I want ask u for the version of CocoaAsyncSocket. . In the file of your project for PaperTrailLumberjack.podspec. 

  s.dependency 'CocoaLumberjack', '~> 2.2.0'
  s.dependency 'CocoaAsyncSocket'

what 's the version of CocoaAsyncSocket ?

**Comment by ghost** [comment]
I solved this problem, with Carthage to manage this framework will not be a problem
