### ISSUE TITLE
Push this fork to cocoapods

### ISSUE THREAD

**Issue by cgreening** [greenbits/papertrail-lumberjack-ios#2]
As far as I can tell the original bitbucket version is no longer maintained.

Do you think it's worth getting in touch with the original author and taking over the maintanence.

If he doesn't respond then it's possible to claim the pod - http://blog.cocoapods.org/Claim-Your-Pods/

Alternatively, change the name of this project's podspec so that it doesn't collide with the old pod.

**Comment by trobrock** [comment]
@cgreening Just pinged him here https://bitbucket.org/rmonkey/papertraillumberjack/pull-request/1/compatibility-fixes-for-cocoalumberjack-20/diff

I'll give that a week then try and claim the cocoapod if I don't hear from him.

**Comment by trobrock** [comment]
Looks like rmonkey is still planning to retain the cocoapod and will now be checking the repo more often for PR's. I still fully plan to maintain this fork though. @cgreening if you would prefer this fork, I can push a new pod to cocoapods under a new name this weekend.

**Comment by cgreening** [comment]
Fair enough - I don't mind just using a git url in my podspec.

**Comment by trobrock** [comment]
Honestly if you and other will still prefer to use this fork, I will push to cocoapods. It bother me a bit to have to use a git repo in my podspec as well.
