### ISSUE TITLE
Can't install this Pod using the instructions

### ISSUE THREAD

**Issue by operatordevelopment** [greenbits/papertrail-lumberjack-ios#5]
Instructions say to install do the following:

pod 'PaperTrailLumberjack'

This installed 0.1.1, which isn't even a release mentioned on this github repo.

I tried to force it to 1.0.3, which appears to be the latest and got the following response from CocoaPods:

[!] Unable to satisfy the following requirements:
- `PaperTrailLumberjack (= 1.0.3)` required by `Podfile`

**Comment by trobrock** [comment]
Hey you are correct, this is a fork of the Pod and the instructions are actually for that pod. To install this one do a

```
pod 'PaperTrailLumberjack', git: 'https://github.com/greenbits/papertrail-lumberjack-ios'
```

Let me know if that doesn't work. I will try and get the docs updated also.

**Comment by operatordevelopment** [comment]
Yes.  That helped.  Thanks!
