### ISSUE TITLE
CocoaAsyncSocket/AsyncSocket.h not found

### ISSUE THREAD

**Issue by rdv0011** [greenbits/papertrail-lumberjack-ios#9]
There is a build error if the next reference to the sources is provided:
pod 'PaperTrailLumberjack', :git => 'https://github.com/greenbits/papertrail-lumberjack-ios.git'

The error message is: CocoaAsyncSocket/AsyncSocket.h not found.

Currently the class AsyncSocket is deprecated and it is actually is not installed by the pod install command. I believe this reference should be either removed or replaced.

**Comment by ghost** [comment]
You can use Carthage to manage this framework, Carthage is a de-centralized management tool, the use of pod version seems to have problems.

**Comment by andrewkatz** [comment]
Looks like that wasn't being used, so I removed the import. Reopen this issue if you run into a problem with it again.
